Cobot_URL : "https://seekbus.servepics.com:8001/"

Stream:
  Websocket_server: "ws://anubhav.ddns.net:3000"
  Websocket_topic: "/home/server"
 
    
Video_Recorder:
  num_samples: 1            
  data_path: "data/recordings/" 
  video_format: "mp4"      
  video_fps: 5.0            
  video_duration: 5      
  width: 640              
  height: 480             
  save_all_frames: true  

Gemini:
  model_name: 'gemini-1.5-flash-002'
  recording_dir: 'data/captured__frames'
  
Camera:
  D435I:
    India:
      Transformations:
        X:
          - [0.068, -0.986, 0.152, -0.108]
          - [0.998, 0.065, -0.023, 0.0]
          - [0.013, 0.153, 0.988, -0.044]
          - [0.0, 0.0, 0.0, 1.0]
        Y:
          - [-0.47, 0.587, -0.659, 0.73929]
          - [0.877, 0.392, -0.276, -0.16997]
          - [0.096, -0.708, -0.7, 0.86356]
          - [0.0, 0.0, 0.0, 1.0]
      
      Intrinsics:
        Color_Intrinsics:
          width: 640
          height: 480
          ppx: 329.1317443847656
          ppy: 240.29669189453125
          fx: 611.084594726562
          fy: 609.7639770507812
          distortion_model: "rs.distortion.brown_conrady"
          coeff: [0.0, 0.0, 0.0, 0.0, 0.0]

DataBase:
  base_dir: "../RAIT/knowledge_base/"
  grasp: "grasps.csv"
  action: "actions.csv"
  
  
RLEF:
  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBOYW1lIjoiQUkgSGFuZCIsInVzZXJFbWFpbCI6ImFiaGlyYW0ua2FtaW5pQHRlY2hvbHV0aW9uLmNvbSIsInVzZXJJZCI6IjY1MWU1NTZjZWNhZGYzMjY5MzhlZWNkZCIsInNjb3BlT2ZUb2tlbiI6eyJwcm9qZWN0SWQiOiI2NGMxMGE2Mzk1MTEzMjc3OTI1YTgwZGYiLCJzY29wZXMiOnsicHJvamVjdCI6eyJyZWFkIjp0cnVlLCJ1cGRhdGUiOnRydWUsImRlbGV0ZSI6dHJ1ZSwiY3JlYXRlIjp0cnVlfSwicmVzb3VyY2UiOnsicmVhZCI6dHJ1ZSwidXBkYXRlIjp0cnVlLCJkZWxldGUiOnRydWUsImNyZWF0ZSI6dHJ1ZX0sIm1vZGVsIjp7InJlYWQiOnRydWUsInVwZGF0ZSI6dHJ1ZSwiZGVsZXRlIjp0cnVlLCJjcmVhdGUiOnRydWV9LCJkYXRhU2V0Q29sbGVjdGlvbiI6eyJyZWFkIjp0cnVlLCJ1cGRhdGUiOnRydWUsImRlbGV0ZSI6dHJ1ZSwiY3JlYXRlIjp0cnVlfSwibW9kZWxDb2xsZWN0aW9uIjp7InJlYWQiOnRydWUsInVwZGF0ZSI6dHJ1ZSwiZGVsZXRlIjp0cnVlLCJjcmVhdGUiOnRydWV9LCJ0ZXN0Q29sbGVjdGlvbiI6eyJyZWFkIjp0cnVlLCJ1cGRhdGUiOnRydWUsImRlbGV0ZSI6dHJ1ZSwiY3JlYXRlIjp0cnVlfSwiY29waWxvdCI6eyJyZWFkIjp0cnVlLCJ1cGRhdGUiOnRydWUsImRlbGV0ZSI6dHJ1ZSwiY3JlYXRlIjp0cnVlfSwiY29waWxvdFJlc291cmNlIjp7InJlYWQiOnRydWUsInVwZGF0ZSI6dHJ1ZSwiZGVsZXRlIjp0cnVlLCJjcmVhdGUiOnRydWV9LCJtb2RlbEdyb3VwIjp7InJlYWQiOnRydWUsInVwZGF0ZSI6dHJ1ZSwiZGVsZXRlIjp0cnVlLCJjcmVhdGUiOnRydWV9fX0sImlhdCI6MTczOTM3MzA1NX0.Q-CIyVoOAw6FmSIPeWn3_PGruLQLkp1e5xvfvSs4LHs"
  task_type: "videoAnnotation"
  model_group_id: "678a262dc441e0b2c81a9686"
  project_id: "64c10a6395113277925a80df"
  
GCP_BUCKET_JSON:
  path: "../config/ai-hand.json"