import cv2
from enum import Enum

class RGBCameraSettings(Enum):
    WIDTH = cv2.CAP_PROP_FRAME_WIDTH
    HEIGHT = cv2.CAP_PROP_FRAME_HEIGHT
    BRIGHTNESS = cv2.CAP_PROP_BRIGHTNESS
    CONTRAST = cv2.CAP_PROP_CONTRAST
    SATURATION = cv2.CAP_PROP_SATURATION
    HUE = cv2.CAP_PROP_HUE
    GAIN = cv2.CAP_PROP_GAIN
    EXPOSURE = cv2.CAP_PROP_EXPOSURE
    WHITE_BALANCE = cv2.CAP_PROP_WHITE_BALANCE_BLUE_U
    FOCUS = cv2.CAP_PROP_FOCUS
    ZOOM = cv2.CAP_PROP_ZOOM
    SHARPNESS = cv2.CAP_PROP_SHARPNESS
    BACKLIGHT = cv2.CAP_PROP_BACKLIGHT
    PAN = cv2.CAP_PROP_PAN
    TILT = cv2.CAP_PROP_TILT
    ROLL = cv2.CAP_PROP_ROLL
    IRIS = cv2.CAP_PROP_IRIS
    SETTINGS = cv2.CAP_PROP_SETTINGS
    BUFFER_SIZE = cv2.CAP_PROP_BUFFERSIZE
    AUTO_EXPOSURE = cv2.CAP_PROP_AUTO_EXPOSURE
    AUTO_FOCUS = cv2.CAP_PROP_AUTOFOCUS
    AUTO_WHITE_BALANCE = cv2.CAP_PROP_AUTO_WB
    FRAME_RATE = cv2.CAP_PROP_FPS
    FOURCC = cv2.CAP_PROP_FOURCC
    FORMAT = cv2.CAP_PROP_FORMAT
    MODE = cv2.CAP_PROP_MODE